INCOMING: 2013-05-30
AUDIT_SESSION=1078347047
VMODEM=/home/insulaudit/sessions/3-1078347047/vmodem
SHELL=/bin/sh
BASE=/home/insulaudit/session
SSH_CLIENT=32.130.168.91 46809 22
FOO=BAR
PHR_REPO=
WORK_CONF=/home/insulaudit/sessions/3-1078347047/conf
WORK_REMOTE=/home/insulaudit/sessions/3-1078347047/remote.git
WORK_LOCAL=/home/insulaudit/sessions/3-1078347047/local
BRANCH=audit/2013-05-30-3-1078347047
USER=insulaudit
AUDIT_USER=ehwest
SESSION_CONFIG=/home/insulaudit/sessions/3-1078347047/conf/audit.config
MAIL=/var/mail/insulaudit
PATH=/home/insulaudit/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
PWD=/home/insulaudit
LANG=en_US.UTF-8
HOME=/home/insulaudit
SHLVL=2
SSH_ORIGINAL_COMMAND=audit 1078347047 3
LOGNAME=insulaudit
SSH_CONNECTION=32.130.168.91 46809 10.170.185.103 22
AUDIT_UID=3
WORK_BASE=/home/insulaudit/sessions/3-1078347047
SESS_KEY=3-1078347047
AUDIT_TOOL=audit
_=/usr/bin/env
mini.py --output /home/insulaudit/sessions/3-1078347047/sugars.txt /home/insulaudit/sessions/3-1078347047/vmodem
is open? True
 timeout: 0.5
Initial DISCONNECT
GETTING FIRMWARE INFO
FIRMWARE IS: P02.00.0025/05/07

read serial number
serial number: DLG8224ER

number of available records:
max records: 9

all records
record: 0
2013-05-30T10:45:43	120
record: 1
2013-05-29T22:30:11	220
record: 2
2013-05-28T23:44:50	175
record: 3
Traceback (most recent call last):
  File "/home/insulaudit/bin/mini.py", line 73, in <module>
    port = init(args)
  File "/home/insulaudit/bin/mini.py", line 50, in init
    r = mini.execute( lsultramini.ReadGlucoseRecord(idx=x ) )
  File "/home/bewest/src/insulaudit/src/insulaudit/devices/lsultramini.py", line 196, in execute
    return command.decode( response )
  File "/home/bewest/src/insulaudit/src/insulaudit/devices/lsultramini.py", line 108, in decode
    date = time.ctime( ls_long( data[ 2:6 ] ) )
  File "/home/bewest/src/insulaudit/src/insulaudit/devices/lsultramini.py", line 35, in ls_long
    return lib.BangLong( B )
  File "/home/bewest/src/insulaudit/src/insulaudit/lib.py", line 177, in BangLong
    ( a, b, c, d ) = bytez
ValueError: need more than 0 values to unpack
